android.experimental.enableNewResourceShrinker.preciseShrinking=true
android.enableAppCompileTimeRClass=true
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=37.0
org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.vfs.watch=true
android.r8.maxWorkers=4
android.native.buildOutput=verbose

# 固定签名（仓库内置 keystore），保证每次构建的 APK 签名一致、可覆盖安装
KEYSTORE_FILE=ksu-debug.jks
KEYSTORE_PASSWORD=android
KEY_ALIAS=debug
KEY_PASSWORD=android
